### ISSUE TITLE
Crafting Table not working

### ISSUE THREAD

**Issue by GitCat3** [Minecraft-in-python/Minecraft#19]
when I try to right click the crafting table, I get the following error: 
```
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000016421C1D1F0>
Traceback (most recent call last):
  File "C:\Users\ironh\Downloads\mip\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 720, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\ironh\Downloads\mip\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 838, in _event_raw_input
    self.dispatch_event('on_mouse_press', 0, 0, mouse.RIGHT,
  File "C:\Users\ironh\Downloads\mip\venv\lib\site-packages\pyglet\window\__init__.py", line 1343, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\ironh\Downloads\mip\venv\lib\site-packages\pyglet\event.py", line 420, in dispatch_event
    raise e
  File "C:\Users\ironh\Downloads\mip\venv\lib\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\ironh\Downloads\mip\Minecraft\Minecraft\game.py", line 347, in on_mouse_press
    self.player.on_mouse_press(x, y, button, modifiers)
  File "C:\Users\ironh\Downloads\mip\Minecraft\Minecraft\player.py", line 135, in on_mouse_press
    block.on_use()
  File "C:\Users\ironh\Downloads\mip\Minecraft\Minecraft\world\block.py", line 241, in on_use
    get_game().toogle_gui('bag')
AttributeError: 'Game' object has no attribute 'toogle_gui'
```
is this just something that is not implemented yet, or am I doing something wrong? Thanks!

**Comment by jason-bowen-zheng** [comment]
Maybe you do something wrong.

**Comment by GitCat3** [comment]
is there any way to tell what it is i'm doing wrong

**Comment by jason-bowen-zheng** [comment]
Oh, It has a spelling mistake.

**Comment by jason-bowen-zheng** [comment]
`toogle_gui` => `toggle_gui`

**Comment by GitCat3** [comment]
so I just have to edit the code of the crafting table?

**Comment by jason-bowen-zheng** [comment]
Yes, The latest commit fixed this bug.

**Comment by GitCat3** [comment]
cool thanks! BTW I put an issue on the pyforge page too.
